export const GAMEBOOKS = [
  'O Feiticeiro da Montanha de Fogo',
  'A Cidadela do Caos',
  'A Masmorra da Morte',
  'Criatura Selvagem',
  'A Cidade dos Ladrões',
  'A Cripta do Feiticeiro',
  'A Mansão do Inferno',
  'A Floresta da Destruição',
  'As Cavernas da Bruxa da Neve',
  'Desafio dos Campeões',
  'Exércitos da Morte',
  'Retorno à Montanha de Fogo',
  'A Ilha do Rei Lagarto',
  'Encontro Marcado com o M.E.D.O.',
  'Nave Espacial Traveller',
  'A Espada do Samurai',
  'Guerreiro das Estradas',
  'O Templo do Terror',
  'Sangue de Zumbis',
  'Ossos Sangrentos',
  'Uivo do Lobisomem',
  'O Porto do Perigo',
  'O Talismã da Morte',
  'A Lenda de Zagor',
  'A Cripta do Vampiro',
  'Algoz da Tempestade',
  'Noite do Necromante',
  'Assassinos de Allansia',
  'Segredos de Salamonis',
  'Sombra de Gigantes',
  'A Masmorra na Ilha de Sangue',
  'Ladrão da Meia-Noite',
  'As Coligações de Kether',
  'Mares de Sangue',
  // Série Magia! (Sorcery!):
  'As Montanhas Shamutanti',
  'Kharé: Porto dos Ardis',
  'As Sete Serpentes',
  'A Coroa dos Reis'
] as const;

export type Gamebook = typeof GAMEBOOKS[number];
