export const victoryParagraphs: Record<string, string[]> = {
  'O Feiticeiro da Montanha de Fogo': ['400'],
  'A Cidadela do Caos': ['400'],
  'A Masmorra da Morte': ['400'],
  'Criatura Selvagem': ['460'],
  'A Cidade dos Ladrões': ['400'],
  'A Cripta do Feiticeiro': ['400'],
  'A Mansão do Inferno': ['400'],
  'A Floresta da Destruição': ['400'],
  'As Cavernas da Bruxa da Neve': ['400'],
  'Desafio dos Campeões': ['400'],
  'Exércitos da Morte': ['400'],
  'Retorno à Montanha de Fogo': ['400'],
  'A Ilha do Rei Lagarto': ['400'],
  'Encontro Marcado com o M.E.D.O.': ['440', '400'],
  'Nave Espacial Traveller': ['400'],
  'A Espada do Samurai': ['400'],
  'Guerreiro das Estradas': ['400'],
  'O Templo do Terror': ['400'],
  'Sangue de Zumbis': ['400'],
  'Ossos Sangrentos': ['400'],
  'Uivo do Lobisomem': ['400'],
  'O Porto do Perigo': ['400'],
  'O Talismã da Morte': ['400'],
  'A Lenda de Zagor': ['400'],
  'A Cripta do Vampiro': ['400'],
  'Algoz da Tempestade': ['400'],
  'Noite do Necromante': ['400'],
  'Assassinos de Allansia': ['400'],
  'Segredos de Salamonis': ['400'],
  'Sombra de Gigantes': ['400'],
  'A Masmorra na Ilha de Sangue': ['400'],
  'Ladrão da Meia-Noite': ['400'],
  'As Coligações de Kether': ['400'],
  'Mares de Sangue': ['400'],
  'As Montanhas Shamutanti': ['400'],
  'Kharé: Porto dos Ardis': ['400'],
  'As Sete Serpentes': ['400'],
  'A Coroa dos Reis': ['400'],
  'Robô Comando': ['400']
};
